set(SRC_FILES
    AppUpdate.cpp
    AppStart.cpp
    Character.cpp
    BGM.cpp
    SoundEffect.cpp
    DynamicBackground.cpp
    Button.cpp
    Scene.cpp
    BirdLaunchController.cpp
    SceneInputController.cpp
    LevelParser.cpp
    LevelObjectFactory.cpp
    GameScene.cpp
    IntroScene.cpp
    LevelManager.cpp
    Resource.cpp
)

set(INCLUDE_FILES
    App.hpp
    BackgroundImage.hpp
    Character.hpp
    BGM.hpp
    SoundEffect.hpp
    DynamicBackground.hpp
    Button.hpp
    Scene.hpp
    BirdLaunchController.hpp
    SceneInputController.hpp
    LevelTypes.hpp
    LevelParser.hpp
    LevelObjectFactory.hpp
    GameScene.hpp
    IntroScene.hpp
    LevelManager.hpp
)

set(TEST_FILES
)
