set(SRC_FILES
    app/AppUpdate.cpp
    app/AppStart.cpp
    entities/Character.cpp
    audio/BGM.cpp
    audio/SoundEffect.cpp
    graphics/DynamicBackground.cpp
    ui/Button.cpp
    ui/AnimatedButton.cpp
    scenes/Scene.cpp
    scenes/CollisionUtils.cpp
    scenes/CollisionResponse.cpp
    scenes/SleepSupport.cpp
    controllers/BirdLaunchController.cpp
    controllers/SceneInputController.cpp
    parsers/JsonParseUtils.cpp
    parsers/LayoutParseUtils.cpp
    parsers/EntityTemplateParser.cpp
    ui/UILayout.cpp
    ui/IntroLayout.cpp
    levels/LevelParser.cpp
    levels/LevelObjectFactory.cpp
    entities/EntityTemplateDatabase.cpp
    scenes/GameScene.cpp
    scenes/IntroScene.cpp
    levels/LevelManager.cpp
    system/Resource.cpp
)

set(INCLUDE_FILES
    app/App.hpp
    graphics/BackgroundImage.hpp
    entities/Character.hpp
    audio/BGM.hpp
    audio/SoundEffect.hpp
    graphics/DynamicBackground.hpp
    ui/Button.hpp
    ui/AnimatedButton.hpp
    scenes/Scene.hpp
    scenes/CollisionUtils.hpp
    scenes/CollisionResponse.hpp
    scenes/SleepSupport.hpp
    scenes/DebugUtils.hpp
    controllers/BirdLaunchController.hpp
    controllers/SceneInputController.hpp
    parsers/JsonParseUtils.hpp
    parsers/LayoutTypes.hpp
    parsers/LayoutParseUtils.hpp
    parsers/EntityTemplateParser.hpp
    entities/EntityTemplateTypes.hpp
    entities/EntityTemplateDatabase.hpp
    ui/UILayout.hpp
    ui/IntroLayout.hpp
    levels/LevelTypes.hpp
    levels/LevelParser.hpp
    levels/LevelObjectFactory.hpp
    scenes/GameScene.hpp
    scenes/IntroScene.hpp
    levels/LevelManager.hpp
    system/Resource.hpp
)

set(TEST_FILES
)
